#!/bin/bash
#
#Aja järgi tervitamine
#
echo -n "Sisesta kellaaeg tundides:"
read aeg 
if [ $aeg -ge 12 -a $aeg -lt 18] ; then
echo "Tere paevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ] ; then
echo "Tere ohtust!"
elid [$aeg -ge 22 -a $aeg -lt 24 ]|| [$aeg -ge 0 -a $aeg -lt 6 ]; then
echo "Head ood!"
else 
echo "Vale sisend"
fi
#
#Skirpi lopp
#
