#!/bin/sh
#
# paarsuse kontroll
#
echo  -n "Sisesta suvaline täisarv: "
read arv
# arvutame jääk 2-ga jagamisel 
jaak=$(( $arv %2))
# 4 % 2 = --> paaris arv
# 5 % 2 = --> paaritu arv
if [ $jaak -eq 0]
siis
echo "$arv on paaris"
või 
echo "$arv on paaritu"
fi
#Skirpti lõpp
