#!/bin/bash
#
#Algarvu tuvastamine
#
echo -e "Sisesta suvaline arv: /c"
read arv
if [$arv -eq 0 -o $arv -eq ] ; then
echo "$arv - ei ole algarv"
else
echo "$arv - on algarv"
fi
if [ $arv -eq $summa ]; then
echo "$arv on algarv"
fi
while [ $summa -lt $arv ]
do
if [ `expr $arv % $summa` -eq 0]
then
echo "$arv ei ole algarv"
exit
fi
summa=$(($summa +1 ))
echo "$arv on algarv"
exit
done
#
#
#
