#!/bin/bash
#
# Skript, mis küsib kasutaja käest tema nimi ja tervitab teda
echo -n "Sisesta oma ees- ja perenimi:"
read eesnimi perenimi
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi"
#
#lõpp

